/*
ProductHub Manager - Security Module Tables and Constraints
Target DBMS: Oracle Database 21c+
*/

------------------------------------------------------------
-- Security lookup tables
------------------------------------------------------------

CREATE TABLE ph_sec_user_type_lkp (
    user_type_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    user_type_name_en VARCHAR2(100 CHAR) NOT NULL,
    user_type_name_ar VARCHAR2(100 CHAR) NOT NULL,
    is_active         NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted        NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at        TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by        NUMBER,
    updated_at        TIMESTAMP(3),
    deleted_by        NUMBER,
    deleted_at        TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_user_type_lkp PRIMARY KEY (user_type_id)
);

------------------------------------------------------------
-- Security tables
------------------------------------------------------------

CREATE TABLE ph_sec_object_type_lkp (
    object_type_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    object_type_name_en VARCHAR2(100 CHAR) NOT NULL,
    object_type_name_ar VARCHAR2(100 CHAR) NOT NULL,
    is_active           NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted          NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at          TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          NUMBER,
    updated_at          TIMESTAMP(3),
    deleted_by          NUMBER,
    deleted_at          TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_object_type_lkp PRIMARY KEY (object_type_id)
);

CREATE TABLE ph_sec_objects (
    object_id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    parent_object_id NUMBER(19),
    object_name      VARCHAR2(128 CHAR) NOT NULL,
    object_type_id   NUMBER(10) NOT NULL,
    object_path      VARCHAR2(300 CHAR) NOT NULL,
    display_name_en  VARCHAR2(200 CHAR) NOT NULL,
    display_name_ar  VARCHAR2(200 CHAR) NOT NULL,
    description_en   VARCHAR2(500 CHAR),
    description_ar   VARCHAR2(500 CHAR),
    is_active        NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted       NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at       TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by       NUMBER,
    updated_at       TIMESTAMP(3),
    deleted_by       NUMBER,
    deleted_at       TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_objects PRIMARY KEY (object_id),
    CONSTRAINT uk_ph_sec_objects_name UNIQUE (object_name),
    CONSTRAINT uk_ph_sec_objects_path UNIQUE (object_path),
    CONSTRAINT fk_ph_sec_objects_parent FOREIGN KEY (parent_object_id) REFERENCES ph_sec_objects ( object_id ),
    CONSTRAINT fk_ph_sec_objects_type FOREIGN KEY (object_type_id) REFERENCES ph_sec_object_type_lkp ( object_type_id ),
    CONSTRAINT ck_ph_sec_objects_parent CHECK ( parent_object_id IS NULL
        OR parent_object_id <> object_id )
);

CREATE TABLE ph_sec_actions (
    action_id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    action_name     VARCHAR2(80 CHAR) NOT NULL,
    display_name_en VARCHAR2(150 CHAR) NOT NULL,
    display_name_ar VARCHAR2(150 CHAR) NOT NULL,
    description_en  VARCHAR2(500 CHAR),
    description_ar  VARCHAR2(500 CHAR),
    is_active       NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted      NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at      TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP(3),
    deleted_by      NUMBER,
    deleted_at      TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_actions PRIMARY KEY (action_id),
    CONSTRAINT uk_ph_sec_actions_name UNIQUE (action_name)
);

CREATE TABLE ph_sec_permissions (
    permission_id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    object_id          NUMBER(19) NOT NULL,
    action_id          NUMBER(19) NOT NULL,
    permission_name_en VARCHAR2(200 CHAR) NOT NULL,
    permission_name_ar VARCHAR2(200 CHAR) NOT NULL,
    description_en     VARCHAR2(500 CHAR),
    description_ar     VARCHAR2(500 CHAR),
    is_active          NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted         NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at         TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by         NUMBER,
    updated_at         TIMESTAMP(3),
    deleted_by         NUMBER,
    deleted_at         TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_permissions PRIMARY KEY (permission_id),
    CONSTRAINT uk_ph_sec_permissions UNIQUE (object_id, action_id),
    CONSTRAINT fk_ph_sec_perm_object FOREIGN KEY (object_id) REFERENCES ph_sec_objects ( object_id ),
    CONSTRAINT fk_ph_sec_perm_action FOREIGN KEY (action_id) REFERENCES ph_sec_actions ( action_id )
);

CREATE TABLE ph_sec_apex_page_type_lkp (
    apex_page_type_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    apex_page_type_code    VARCHAR2(50 CHAR) NOT NULL,
    apex_page_type_name_en VARCHAR2(100 CHAR) NOT NULL,
    apex_page_type_name_ar VARCHAR2(100 CHAR) NOT NULL,
    is_active             NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted            NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at            TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by            NUMBER,
    updated_at            TIMESTAMP(3),
    deleted_by            NUMBER,
    deleted_at            TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_apex_page_type PRIMARY KEY (apex_page_type_id),
    CONSTRAINT uk_ph_sec_apex_page_type_code UNIQUE (apex_page_type_code),
    CONSTRAINT ck_ph_sec_apex_ptype_active CHECK ( is_active IN (0, 1) )
);

CREATE TABLE ph_sec_users (
    user_id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    customer_id          NUMBER(19),
    user_type            NUMBER(10) NOT NULL,
    email                VARCHAR2(320 CHAR) NOT NULL,
    display_name         VARCHAR2(200 CHAR) NOT NULL,
    password_hash        raw(512),
    password_salt        raw(256),
    must_change_password NUMBER(1) DEFAULT 1 NOT NULL,
    is_initial_admin     NUMBER(1) DEFAULT 0 NOT NULL,
    is_active            NUMBER(1) DEFAULT 1 NOT NULL,
    last_login_at        TIMESTAMP(3),
    is_deleted           NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at           TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by           NUMBER,
    updated_at           TIMESTAMP(3),
    deleted_by           NUMBER,
    deleted_at           TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_users PRIMARY KEY (user_id),
    CONSTRAINT uk_ph_sec_users_email UNIQUE (email),
    CONSTRAINT fk_ph_sec_users_customer FOREIGN KEY (customer_id) REFERENCES ph_erp_customers ( customer_id ),
    CONSTRAINT fk_ph_sec_users_type FOREIGN KEY (user_type) REFERENCES ph_sec_user_type_lkp ( user_type_id ),
    CONSTRAINT ck_ph_sec_users_email_lower CHECK ( email = LOWER(email) ),
    CONSTRAINT ck_ph_sec_users_flags CHECK ( must_change_password IN (0, 1)
        AND is_initial_admin IN (0, 1) )
);

CREATE TABLE ph_sec_user_preferences (
    user_id          NUMBER(19) NOT NULL,
    preference_code  VARCHAR2(80 CHAR) NOT NULL,
    preference_value VARCHAR2(4000 CHAR),
    value_type       VARCHAR2(20 CHAR) DEFAULT 'STRING' NOT NULL,
    is_active        NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted       NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at       TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by       NUMBER,
    updated_at       TIMESTAMP(3),
    deleted_by       NUMBER,
    deleted_at       TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_user_preferences PRIMARY KEY (user_id, preference_code),
    CONSTRAINT fk_ph_sec_user_pref_user FOREIGN KEY (user_id) REFERENCES ph_sec_users ( user_id ),
    CONSTRAINT ck_ph_sec_user_pref_code CHECK ( preference_code = UPPER(preference_code) ),
    CONSTRAINT ck_ph_sec_user_pref_type CHECK ( value_type IN ( 'STRING',
    'NUMBER',
    'BOOLEAN',
    'JSON' ) ),
    CONSTRAINT ck_ph_sec_user_pref_active CHECK ( is_active IN (0, 1) )
);

CREATE TABLE ph_sec_refresh_tokens (
    refresh_token_id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    user_id              NUMBER(19) NOT NULL,
    token_hash           RAW(32) NOT NULL,
    issued_at            TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at           TIMESTAMP(3) NOT NULL,
    revoked_at           TIMESTAMP(3),
    replaced_by_token_id NUMBER(19),
    created_by           NUMBER,
    created_at           TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by           NUMBER,
    updated_at           TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_refresh_tokens PRIMARY KEY (refresh_token_id),
    CONSTRAINT uk_ph_sec_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_ph_sec_rt_user FOREIGN KEY (user_id) REFERENCES ph_sec_users ( user_id ),
    CONSTRAINT fk_ph_sec_rt_replaced_by FOREIGN KEY (replaced_by_token_id) REFERENCES ph_sec_refresh_tokens ( refresh_token_id ),
    CONSTRAINT ck_ph_sec_rt_dates CHECK (expires_at > issued_at)
);

CREATE TABLE ph_sec_password_reset_tokens (
    reset_token_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    user_id        NUMBER(19) NOT NULL,
    token_hash     RAW(32) NOT NULL,
    issued_at      TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at     TIMESTAMP(3) NOT NULL,
    used_at        TIMESTAMP(3),
    created_by     NUMBER,
    created_at     TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by     NUMBER,
    updated_at     TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_password_reset_tokens PRIMARY KEY (reset_token_id),
    CONSTRAINT uk_ph_sec_prt_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_ph_sec_prt_user FOREIGN KEY (user_id) REFERENCES ph_sec_users ( user_id ),
    CONSTRAINT ck_ph_sec_prt_dates CHECK (expires_at > issued_at)
);

CREATE TABLE ph_sec_apex_pages (
    apex_page_id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    apex_app_id       NUMBER(10) NOT NULL,
    apex_page_no      NUMBER(10) NOT NULL,
    apex_page_type_id NUMBER(10) NOT NULL,
    page_alias        VARCHAR2(128 CHAR),
    page_name_en      VARCHAR2(200 CHAR) NOT NULL,
    page_name_ar      VARCHAR2(200 CHAR) NOT NULL,
    object_path       VARCHAR2(300 CHAR),
    access_mode       VARCHAR2(20 CHAR) DEFAULT 'ANY' NOT NULL,
    is_public         NUMBER(1) DEFAULT 0 NOT NULL,
    is_active         NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted        NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at        TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by        NUMBER,
    updated_at        TIMESTAMP(3),
    deleted_by        NUMBER,
    deleted_at        TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_apex_pages PRIMARY KEY (apex_page_id),
    CONSTRAINT uk_ph_sec_apex_pages_app_page UNIQUE (apex_app_id, apex_page_no),
    CONSTRAINT uk_ph_sec_apex_pages_alias UNIQUE (apex_app_id, page_alias),
    CONSTRAINT fk_ph_sec_apex_pages_type FOREIGN KEY (apex_page_type_id) REFERENCES ph_sec_apex_page_type_lkp ( apex_page_type_id ),
    CONSTRAINT ck_ph_sec_apex_pages_ids CHECK ( apex_app_id > 0
        AND apex_page_no >= 0 ),
    CONSTRAINT ck_ph_sec_apex_pages_mode CHECK ( access_mode IN ('ANY', 'ALL') ),
    CONSTRAINT ck_ph_sec_apex_pages_flags CHECK ( is_public IN (0, 1)
        AND is_active IN (0, 1) )
);

CREATE TABLE ph_sec_apex_page_permissions (
    apex_page_id            NUMBER(19) NOT NULL,
    permission_id           NUMBER(19) NOT NULL,
    is_an_access_permission NUMBER(1) DEFAULT 1 NOT NULL,
    is_active               NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted              NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at              TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by              NUMBER,
    updated_at              TIMESTAMP(3),
    deleted_by              NUMBER,
    deleted_at              TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_apex_page_perm PRIMARY KEY (apex_page_id, permission_id),
    CONSTRAINT fk_ph_sec_app_perm_page FOREIGN KEY (apex_page_id) REFERENCES ph_sec_apex_pages ( apex_page_id ),
    CONSTRAINT fk_ph_sec_app_perm_perm FOREIGN KEY (permission_id) REFERENCES ph_sec_permissions ( permission_id ),
    CONSTRAINT ck_ph_sec_app_perm_active CHECK ( is_active IN (0, 1) ),
    CONSTRAINT ck_ph_sec_app_perm_access CHECK ( is_an_access_permission IN (0, 1) )
);

CREATE TABLE ph_sec_roles (
    role_id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    role_name_en   VARCHAR2(150 CHAR) NOT NULL,
    role_name_ar   VARCHAR2(150 CHAR) NOT NULL,
    description_en VARCHAR2(500 CHAR),
    description_ar VARCHAR2(500 CHAR),
    user_type      NUMBER(10) NOT NULL,
    is_system_role NUMBER(1) DEFAULT 0 NOT NULL,
    is_active      NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted     NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at     TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by     NUMBER,
    updated_at     TIMESTAMP(3),
    deleted_by     NUMBER,
    deleted_at     TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_roles PRIMARY KEY (role_id),
    CONSTRAINT fk_ph_sec_roles_type FOREIGN KEY (user_type) REFERENCES ph_sec_user_type_lkp ( user_type_id ),
    CONSTRAINT ck_ph_sec_roles_system CHECK ( is_system_role IN (0, 1) )
);

CREATE TABLE ph_sec_role_permissions (
    role_id       NUMBER(19) NOT NULL,
    permission_id NUMBER(19) NOT NULL,
    is_deleted    NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at    TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by    NUMBER,
    updated_at    TIMESTAMP(3),
    deleted_by    NUMBER,
    deleted_at    TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_ph_sec_rp_role FOREIGN KEY (role_id) REFERENCES ph_sec_roles ( role_id ),
    CONSTRAINT fk_ph_sec_rp_permission FOREIGN KEY (permission_id) REFERENCES ph_sec_permissions ( permission_id )
);

CREATE TABLE ph_sec_user_roles (
    user_id     NUMBER(19) NOT NULL,
    role_id     NUMBER(19) NOT NULL,
    assigned_by NUMBER(19),
    assigned_at TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    is_deleted  NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at  TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by  NUMBER,
    updated_at  TIMESTAMP(3),
    deleted_by  NUMBER,
    deleted_at  TIMESTAMP(3),
    CONSTRAINT pk_ph_sec_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_ph_sec_ur_user FOREIGN KEY (user_id) REFERENCES ph_sec_users ( user_id ),
    CONSTRAINT fk_ph_sec_ur_role FOREIGN KEY (role_id) REFERENCES ph_sec_roles ( role_id )
);

------------------------------------------------------------
-- Security active flag checks
------------------------------------------------------------

ALTER TABLE ph_sec_user_type_lkp
ADD CONSTRAINT ck_ph_sec_user_type_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_sec_object_type_lkp
ADD CONSTRAINT ck_ph_sec_obj_type_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_sec_objects
ADD CONSTRAINT ck_ph_sec_objects_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_sec_actions
ADD CONSTRAINT ck_ph_sec_actions_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_sec_permissions
ADD CONSTRAINT ck_ph_sec_permissions_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_sec_users
ADD CONSTRAINT ck_ph_sec_users_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_sec_roles
ADD CONSTRAINT ck_ph_sec_roles_active CHECK ( is_active IN (0, 1) );
