/*
ProductHub Manager - Oracle Tables and Constraints
Target DBMS: Oracle Database 21c+

Naming:
- ERP/business tables use PH_ERP_ prefix.
- Security/auth tables use PH_SEC_ prefix.
- Lookup tables use _LKP postfix.
- Default Arabic/English text is stored in *_EN and *_AR columns.
- Additional languages are stored in PH_I18N_TEXTS by table/entity/field.
- Active flags use: is_active NUMBER(1) DEFAULT 1 NOT NULL with CHECK (is_active IN (0, 1)).
- Soft delete flags use: is_deleted NUMBER(1) DEFAULT 0 NOT NULL with CHECK (is_deleted IN (0, 1)).
*/

------------------------------------------------------------
-- Lookup tables
------------------------------------------------------------
CREATE TABLE ph_languages (
    language_code VARCHAR2(20 CHAR) NOT NULL,
    language_name VARCHAR2(100 CHAR) NOT NULL,
    native_name   VARCHAR2(100 CHAR),
    is_rtl        NUMBER(1) DEFAULT 0 NOT NULL,
    is_default    NUMBER(1) DEFAULT 0 NOT NULL,
    is_active     NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted    NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at    TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by    NUMBER,
    updated_at    TIMESTAMP(3),
    deleted_by    NUMBER,
    deleted_at    TIMESTAMP(3),
    CONSTRAINT pk_ph_languages PRIMARY KEY (language_code),
    CONSTRAINT ck_ph_languages_code CHECK ( language_code = LOWER(language_code) ),
    CONSTRAINT ck_ph_languages_flags CHECK ( is_rtl IN (0, 1)
        AND is_default IN (0, 1)
        AND is_active IN (0, 1) )
);

CREATE TABLE ph_i18n_texts (
    i18n_text_id  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    entity_name   VARCHAR2(128 CHAR) NOT NULL,
    entity_key    VARCHAR2(400 CHAR) NOT NULL,
    field_name    VARCHAR2(128 CHAR) NOT NULL,
    language_code VARCHAR2(20 CHAR) NOT NULL,
    text_value    VARCHAR2(4000 CHAR),
    is_deleted    NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at    TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by    NUMBER,
    updated_at    TIMESTAMP(3),
    deleted_by    NUMBER,
    deleted_at    TIMESTAMP(3),
    CONSTRAINT pk_ph_i18n_texts PRIMARY KEY (i18n_text_id),
    CONSTRAINT uk_ph_i18n_texts UNIQUE (entity_name, entity_key, field_name, language_code),
    CONSTRAINT fk_ph_i18n_language FOREIGN KEY (language_code) REFERENCES ph_languages ( language_code ),
    CONSTRAINT ck_ph_i18n_names CHECK ( entity_name = UPPER(entity_name)
        AND field_name = UPPER(field_name)
        AND language_code = LOWER(language_code) )
);

CREATE TABLE ph_i18n_messages (
    message_code  VARCHAR2(100 CHAR) NOT NULL,
    language_code VARCHAR2(20 CHAR) NOT NULL,
    message_text  VARCHAR2(4000 CHAR) NOT NULL,
    is_deleted    NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at    TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by    NUMBER,
    updated_at    TIMESTAMP(3),
    deleted_by    NUMBER,
    deleted_at    TIMESTAMP(3),
    CONSTRAINT pk_ph_i18n_messages PRIMARY KEY (message_code, language_code),
    CONSTRAINT fk_ph_i18n_msg_language FOREIGN KEY (language_code) REFERENCES ph_languages ( language_code ),
    CONSTRAINT ck_ph_i18n_msg_code CHECK ( message_code = UPPER(message_code)
        AND language_code = LOWER(language_code) )
);

CREATE TABLE ph_lookup_types (
    lookup_type_code VARCHAR2(80 CHAR) NOT NULL,
    lookup_type_name_en VARCHAR2(200 CHAR) NOT NULL,
    lookup_type_name_ar VARCHAR2(200 CHAR) NOT NULL,
    description_en VARCHAR2(500 CHAR),
    description_ar VARCHAR2(500 CHAR),
    is_system_type NUMBER(1) DEFAULT 1 NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by NUMBER,
    created_at TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by NUMBER,
    updated_at TIMESTAMP(3),
    deleted_by NUMBER,
    deleted_at TIMESTAMP(3),
    CONSTRAINT pk_ph_lookup_types PRIMARY KEY (lookup_type_code),
    CONSTRAINT ck_ph_lookup_types_code CHECK ( lookup_type_code = UPPER(lookup_type_code) ),
    CONSTRAINT ck_ph_lookup_types_flags CHECK ( is_system_type IN (0, 1)
        AND is_active IN (0, 1) )
);

CREATE TABLE ph_lookup_values (
    lookup_type_code VARCHAR2(80 CHAR) NOT NULL,
    lookup_value_code VARCHAR2(120 CHAR) NOT NULL,
    display_value_en VARCHAR2(4000 CHAR) NOT NULL,
    display_value_ar VARCHAR2(4000 CHAR) NOT NULL,
    return_value VARCHAR2(4000 CHAR) NOT NULL,
    display_order NUMBER(10) DEFAULT 0 NOT NULL,
    is_system_value NUMBER(1) DEFAULT 1 NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by NUMBER,
    created_at TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by NUMBER,
    updated_at TIMESTAMP(3),
    deleted_by NUMBER,
    deleted_at TIMESTAMP(3),
    CONSTRAINT pk_ph_lookup_values PRIMARY KEY (lookup_type_code, lookup_value_code),
    CONSTRAINT fk_ph_lookup_values_type FOREIGN KEY (lookup_type_code) REFERENCES ph_lookup_types ( lookup_type_code ),
    CONSTRAINT ck_ph_lookup_values_code CHECK ( lookup_value_code = UPPER(lookup_value_code) ),
    CONSTRAINT ck_ph_lookup_values_flags CHECK ( is_system_value IN (0, 1)
        AND is_active IN (0, 1) )
);

------------------------------------------------------------
-- ERP catalog tables
------------------------------------------------------------

------------------------------------------------------------
-- ERP customer AND contract tables
------------------------------------------------------------

------------------------------------------------------------
-- Standard active flag checks
------------------------------------------------------------

------------------------------------------------------------
-- Globalization error logging
------------------------------------------------------------

CREATE TABLE ph_globalization_error_log (
    error_log_id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    error_date              TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    program_unit            VARCHAR2(128 CHAR),
    program_unit_parameters CLOB,
    error_location          VARCHAR2(4000 CHAR),
    error_code              NUMBER,
    error_message           VARCHAR2(4000 CHAR),
    error_stack             CLOB,
    error_backtrace         CLOB,
    call_stack              CLOB,
    module_name             VARCHAR2(64 CHAR) DEFAULT 'GLOBALIZATION' NOT NULL,
    action_name             VARCHAR2(64 CHAR),
    session_user            VARCHAR2(128 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER'),
    current_schema          VARCHAR2(128 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'),
    client_identifier       VARCHAR2(256 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'),
    host_name               VARCHAR2(256 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'HOST'),
    ip_address              VARCHAR2(64 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'IP_ADDRESS'),
    apex_app_id             NUMBER,
    apex_page_id            NUMBER,
    created_at              TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_ph_globalization_error_log PRIMARY KEY (error_log_id)
);

