/*
ProductHub Manager - Contract Module Tables and Constraints
Target DBMS: Oracle Database 21c+
*/

CREATE TABLE ph_erp_contracts (
    contract_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    contract_no   VARCHAR2(80 CHAR) NOT NULL,
    customer_id   NUMBER(19) NOT NULL,
    product_id    NUMBER(19) NOT NULL,
    start_date    DATE NOT NULL,
    end_date      DATE,
    payment_cycle NUMBER(10) NOT NULL,
    is_active     NUMBER(1) DEFAULT 1 NOT NULL,
    notes_en      VARCHAR2(1000 CHAR),
    notes_ar      VARCHAR2(1000 CHAR),
    is_deleted    NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at    TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by    NUMBER,
    updated_at    TIMESTAMP(3),
    deleted_by    NUMBER,
    deleted_at    TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_contracts PRIMARY KEY (contract_id),
    CONSTRAINT uk_ph_erp_contracts_no UNIQUE (contract_no),
    CONSTRAINT uk_ph_erp_contracts_prod UNIQUE (contract_id, product_id),
    CONSTRAINT uk_ph_erp_contracts_cprod UNIQUE (contract_id, customer_id, product_id),
    CONSTRAINT fk_ph_erp_contract_customer FOREIGN KEY (customer_id) REFERENCES ph_erp_customers ( customer_id ),
    CONSTRAINT fk_ph_erp_contract_product FOREIGN KEY (product_id) REFERENCES ph_erp_products ( product_id ),
    CONSTRAINT fk_ph_erp_contract_cycle FOREIGN KEY (payment_cycle) REFERENCES ph_erp_payment_cycle_lkp ( payment_cycle_id ),
    CONSTRAINT ck_ph_erp_contract_dates CHECK ( end_date IS NULL
        OR end_date >= start_date )
);

CREATE TABLE ph_erp_contract_urls (
    contract_url_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    contract_id     NUMBER(19) NOT NULL,
    access_url      VARCHAR2(1000 CHAR) NOT NULL,
    is_primary      NUMBER(1) DEFAULT 1 NOT NULL,
    is_active       NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted      NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at      TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP(3),
    deleted_by      NUMBER,
    deleted_at      TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_contract_urls PRIMARY KEY (contract_url_id),
    CONSTRAINT uk_ph_erp_contract_url UNIQUE (contract_id, access_url),
    CONSTRAINT fk_ph_erp_cu_contract FOREIGN KEY (contract_id) REFERENCES ph_erp_contracts ( contract_id ),
    CONSTRAINT ck_ph_erp_cu_flags CHECK ( is_primary IN (0, 1)
        AND is_active IN (0, 1) )
);

CREATE TABLE ph_erp_contract_modules (
    contract_id    NUMBER(19) NOT NULL,
    product_id     NUMBER(19) NOT NULL,
    module_id      NUMBER(19) NOT NULL,
    is_active      NUMBER(1) DEFAULT 1 NOT NULL,
    effective_from DATE DEFAULT trunc(sysdate) NOT NULL,
    effective_to   DATE,
    is_deleted     NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at     TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by     NUMBER,
    updated_at     TIMESTAMP(3),
    deleted_by     NUMBER,
    deleted_at     TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_contract_modules PRIMARY KEY (contract_id, module_id),
    CONSTRAINT uk_ph_erp_contract_modules UNIQUE (contract_id, product_id, module_id),
    CONSTRAINT fk_ph_erp_cm_contract
    FOREIGN KEY (contract_id, product_id) REFERENCES ph_erp_contracts ( contract_id,
    product_id ),
    CONSTRAINT fk_ph_erp_cm_module
    FOREIGN KEY (product_id, module_id) REFERENCES ph_erp_modules ( product_id,
    module_id ),
    CONSTRAINT ck_ph_erp_cm_dates CHECK ( effective_to IS NULL
        OR effective_to >= effective_from )
);

CREATE TABLE ph_erp_contract_platforms (
    contract_id    NUMBER(19) NOT NULL,
    product_id     NUMBER(19) NOT NULL,
    module_id      NUMBER(19) NOT NULL,
    platform_id    NUMBER(10) NOT NULL,
    is_active      NUMBER(1) DEFAULT 1 NOT NULL,
    effective_from DATE DEFAULT trunc(sysdate) NOT NULL,
    effective_to   DATE,
    is_deleted     NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at     TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by     NUMBER,
    updated_at     TIMESTAMP(3),
    deleted_by     NUMBER,
    deleted_at     TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_contract_platforms
    PRIMARY KEY (contract_id, product_id, module_id, platform_id),
    CONSTRAINT fk_ph_erp_cp_contract_mod
    FOREIGN KEY (contract_id, product_id, module_id) REFERENCES ph_erp_contract_modules ( contract_id,
    product_id,
    module_id ),
    CONSTRAINT fk_ph_erp_cp_module_platform
    FOREIGN KEY (product_id, module_id, platform_id) REFERENCES ph_erp_module_platforms ( product_id,
    module_id,
    platform_id ),
    CONSTRAINT ck_ph_erp_cp_dates CHECK ( effective_to IS NULL
        OR effective_to >= effective_from )
);

CREATE TABLE ph_erp_contract_features (
    contract_id    NUMBER(19) NOT NULL,
    product_id     NUMBER(19) NOT NULL,
    module_id      NUMBER(19) NOT NULL,
    platform_id    NUMBER(10) NOT NULL,
    feature_id     NUMBER(19) NOT NULL,
    agreed_price   NUMBER(18,4),
    is_active      NUMBER(1) DEFAULT 1 NOT NULL,
    effective_from DATE DEFAULT trunc(sysdate) NOT NULL,
    effective_to   DATE,
    is_deleted     NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at     TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by     NUMBER,
    updated_at     TIMESTAMP(3),
    deleted_by     NUMBER,
    deleted_at     TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_contract_features
    PRIMARY KEY (contract_id, product_id, module_id, platform_id, feature_id),
    CONSTRAINT fk_ph_erp_cf_contract_platform
    FOREIGN KEY (contract_id, product_id, module_id, platform_id) REFERENCES ph_erp_contract_platforms ( contract_id,
    product_id,
    module_id,
    platform_id ),
    CONSTRAINT fk_ph_erp_cf_feature
    FOREIGN KEY (product_id, module_id, platform_id, feature_id) REFERENCES ph_erp_features ( product_id,
    module_id,
    platform_id,
    feature_id ),
    CONSTRAINT ck_ph_erp_cf_price CHECK ( agreed_price IS NULL
        OR agreed_price >= 0 ),
    CONSTRAINT ck_ph_erp_cf_dates CHECK ( effective_to IS NULL
        OR effective_to >= effective_from )
);

------------------------------------------------------------
-- Active flag checks
------------------------------------------------------------

ALTER TABLE ph_erp_contracts
ADD CONSTRAINT ck_ph_erp_contracts_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_erp_contract_modules
ADD CONSTRAINT ck_ph_erp_cm_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_erp_contract_platforms
ADD CONSTRAINT ck_ph_erp_cp_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_erp_contract_features
ADD CONSTRAINT ck_ph_erp_cf_active CHECK ( is_active IN (0, 1) );
