/*
ProductHub Manager - Product Module Tables and Constraints
Target DBMS: Oracle Database 21c+
*/

CREATE TABLE ph_erp_pricing_unit_lkp (
    pricing_unit_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    pricing_unit_name_en VARCHAR2(100 CHAR) NOT NULL,
    pricing_unit_name_ar VARCHAR2(100 CHAR) NOT NULL,
    is_active            NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted           NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at           TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by           NUMBER,
    updated_at           TIMESTAMP(3),
    deleted_by           NUMBER,
    deleted_at           TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_pricing_unit_lkp PRIMARY KEY (pricing_unit_id)
);

CREATE TABLE ph_erp_payment_cycle_lkp (
    payment_cycle_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    payment_cycle_name_en VARCHAR2(100 CHAR) NOT NULL,
    payment_cycle_name_ar VARCHAR2(100 CHAR) NOT NULL,
    months_count          NUMBER(3) NOT NULL,
    is_active             NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted            NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at            TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by            NUMBER,
    updated_at            TIMESTAMP(3),
    deleted_by            NUMBER,
    deleted_at            TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_pay_cycle_lkp PRIMARY KEY (payment_cycle_id),
    CONSTRAINT ck_ph_erp_pay_cycle_months CHECK ( months_count > 0 )
);

CREATE TABLE ph_erp_platform_lkp (
    platform_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    platform_name_en VARCHAR2(100 CHAR) NOT NULL,
    platform_name_ar VARCHAR2(100 CHAR) NOT NULL,
    is_active        NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted       NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at       TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by       NUMBER,
    updated_at       TIMESTAMP(3),
    deleted_by       NUMBER,
    deleted_at       TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_platform_lkp PRIMARY KEY (platform_id)
);

CREATE TABLE ph_erp_products (
    product_id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    product_name_en VARCHAR2(200 CHAR) NOT NULL,
    product_name_ar VARCHAR2(200 CHAR) NOT NULL,
    description_en  VARCHAR2(1000 CHAR),
    description_ar  VARCHAR2(1000 CHAR),
    is_active       NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted      NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at      TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP(3),
    deleted_by      NUMBER,
    deleted_at      TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_products PRIMARY KEY (product_id)
);

CREATE TABLE ph_erp_product_module_seq (
    product_id     NUMBER(19) NOT NULL,
    next_module_id NUMBER(19) DEFAULT 1 NOT NULL,
    is_deleted     NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at     TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by     NUMBER,
    updated_at     TIMESTAMP(3),
    deleted_by     NUMBER,
    deleted_at     TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_product_module_seq PRIMARY KEY (product_id),
    CONSTRAINT fk_ph_erp_pms_product FOREIGN KEY (product_id) REFERENCES ph_erp_products ( product_id ),
    CONSTRAINT ck_ph_erp_pms_next CHECK ( next_module_id >= 1 )
);
organization index;

CREATE TABLE ph_erp_modules (
    product_id     NUMBER(19) NOT NULL,
    module_id      NUMBER(19) NOT NULL,
    module_name_en VARCHAR2(200 CHAR) NOT NULL,
    module_name_ar VARCHAR2(200 CHAR) NOT NULL,
    description_en VARCHAR2(1000 CHAR),
    description_ar VARCHAR2(1000 CHAR),
    display_order  NUMBER(10) DEFAULT 0 NOT NULL,
    is_active      NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted     NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at     TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by     NUMBER,
    updated_at     TIMESTAMP(3),
    deleted_by     NUMBER,
    deleted_at     TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_modules PRIMARY KEY (product_id, module_id),
    CONSTRAINT fk_ph_erp_modules_product FOREIGN KEY (product_id) REFERENCES ph_erp_products ( product_id )
);

CREATE TABLE ph_erp_module_platforms (
    product_id  NUMBER(19) NOT NULL,
    module_id   NUMBER(19) NOT NULL,
    platform_id NUMBER(10) NOT NULL,
    is_active   NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted  NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at  TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by  NUMBER,
    updated_at  TIMESTAMP(3),
    deleted_by  NUMBER,
    deleted_at  TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_module_platforms PRIMARY KEY (product_id, module_id, platform_id),
    CONSTRAINT fk_ph_erp_mp_module
    FOREIGN KEY (product_id, module_id) REFERENCES ph_erp_modules ( product_id,
    module_id ),
    CONSTRAINT fk_ph_erp_mp_platform FOREIGN KEY (platform_id) REFERENCES ph_erp_platform_lkp ( platform_id )
);

CREATE TABLE ph_erp_module_feature_seq (
    product_id      NUMBER(19) NOT NULL,
    module_id       NUMBER(19) NOT NULL,
    platform_id     NUMBER(10) NOT NULL,
    next_feature_id NUMBER(19) DEFAULT 1 NOT NULL,
    is_deleted      NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at      TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP(3),
    deleted_by      NUMBER,
    deleted_at      TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_module_feature_seq PRIMARY KEY (product_id, module_id, platform_id),
    CONSTRAINT fk_ph_erp_mfs_mod_plat
    FOREIGN KEY (product_id, module_id, platform_id) REFERENCES ph_erp_module_platforms ( product_id,
    module_id,
    platform_id ),
    CONSTRAINT ck_ph_erp_mfs_next CHECK ( next_feature_id >= 1 )
);
organization index;

CREATE TABLE ph_erp_features (
    product_id      NUMBER(19) NOT NULL,
    module_id       NUMBER(19) NOT NULL,
    platform_id     NUMBER(10) NOT NULL,
    feature_id      NUMBER(19) NOT NULL,
    feature_name_en VARCHAR2(200 CHAR) NOT NULL,
    feature_name_ar VARCHAR2(200 CHAR) NOT NULL,
    description_en  VARCHAR2(1000 CHAR),
    description_ar  VARCHAR2(1000 CHAR),
    price           NUMBER(18,4) NOT NULL,
    pricing_unit_id NUMBER(10) NOT NULL,
    usage_unit      VARCHAR2(50 CHAR) DEFAULT 'USE' NOT NULL,
    display_order   NUMBER(10) DEFAULT 0 NOT NULL,
    is_active       NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted      NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at      TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP(3),
    deleted_by      NUMBER,
    deleted_at      TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_features
    PRIMARY KEY (product_id, module_id, platform_id, feature_id),
    CONSTRAINT fk_ph_erp_features_mod_plat
    FOREIGN KEY (product_id, module_id, platform_id) REFERENCES ph_erp_module_platforms ( product_id,
    module_id,
    platform_id ),
    CONSTRAINT fk_ph_erp_features_unit FOREIGN KEY (pricing_unit_id) REFERENCES ph_erp_pricing_unit_lkp ( pricing_unit_id ),
    CONSTRAINT ck_ph_erp_features_price CHECK ( price >= 0 )
);

------------------------------------------------------------
-- Active flag checks
------------------------------------------------------------

ALTER TABLE ph_erp_pricing_unit_lkp
ADD CONSTRAINT ck_ph_erp_price_unit_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_erp_payment_cycle_lkp
ADD CONSTRAINT ck_ph_erp_pay_cycle_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_erp_platform_lkp
ADD CONSTRAINT ck_ph_erp_platform_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_erp_products
ADD CONSTRAINT ck_ph_erp_products_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_erp_modules
ADD CONSTRAINT ck_ph_erp_modules_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_erp_module_platforms
ADD CONSTRAINT ck_ph_erp_mp_active CHECK ( is_active IN (0, 1) );

ALTER TABLE ph_erp_features
ADD CONSTRAINT ck_ph_erp_features_active CHECK ( is_active IN (0, 1) );

------------------------------------------------------------
-- Product error logging
------------------------------------------------------------

CREATE TABLE ph_erp_product_error_log (
    error_log_id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    error_date              TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    program_unit            VARCHAR2(128 CHAR),
    program_unit_parameters CLOB,
    error_location          VARCHAR2(4000 CHAR),
    error_code              NUMBER,
    error_message           VARCHAR2(4000 CHAR),
    error_stack             CLOB,
    error_backtrace         CLOB,
    call_stack              CLOB,
    module_name             VARCHAR2(64 CHAR) DEFAULT 'PRODUCT' NOT NULL,
    action_name             VARCHAR2(64 CHAR),
    session_user            VARCHAR2(128 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER'),
    current_schema          VARCHAR2(128 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'),
    client_identifier       VARCHAR2(256 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'),
    host_name               VARCHAR2(256 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'HOST'),
    ip_address              VARCHAR2(64 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'IP_ADDRESS'),
    apex_app_id             NUMBER,
    apex_page_id            NUMBER,
    created_at              TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_ph_erp_product_error_log PRIMARY KEY (error_log_id)
);
