/*
ProductHub Manager - Customer Module Tables and Constraints
Target DBMS: Oracle Database 21c+
*/

CREATE TABLE ph_erp_customers (
    customer_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(250 CHAR) NOT NULL,
    legal_name    VARCHAR2(250 CHAR),
    contact_email VARCHAR2(320 CHAR),
    contact_phone VARCHAR2(50 CHAR),
    is_active     NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted    NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at    TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by    NUMBER,
    updated_at    TIMESTAMP(3),
    deleted_by    NUMBER,
    deleted_at    TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_customers PRIMARY KEY (customer_id)
);

------------------------------------------------------------
-- Active flag checks
------------------------------------------------------------

ALTER TABLE ph_erp_customers
ADD CONSTRAINT ck_ph_erp_customers_active CHECK ( is_active IN (0, 1) );

------------------------------------------------------------
-- Customer error logging
------------------------------------------------------------

CREATE TABLE ph_erp_customer_error_log (
    error_log_id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    error_date              TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    program_unit            VARCHAR2(128 CHAR),
    program_unit_parameters CLOB,
    error_location          VARCHAR2(4000 CHAR),
    error_code              NUMBER,
    error_message           VARCHAR2(4000 CHAR),
    error_stack             CLOB,
    error_backtrace         CLOB,
    call_stack              CLOB,
    module_name             VARCHAR2(64 CHAR) DEFAULT 'CUSTOMER' NOT NULL,
    action_name             VARCHAR2(64 CHAR),
    session_user            VARCHAR2(128 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER'),
    current_schema          VARCHAR2(128 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'),
    client_identifier       VARCHAR2(256 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'),
    host_name               VARCHAR2(256 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'HOST'),
    ip_address              VARCHAR2(64 CHAR) DEFAULT SYS_CONTEXT('USERENV', 'IP_ADDRESS'),
    apex_app_id             NUMBER,
    apex_page_id            NUMBER,
    created_at              TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_ph_erp_customer_error_log PRIMARY KEY (error_log_id)
);
