/*
ProductHub Manager - Customer Module Seed Data
Target DBMS: Oracle Database 21c+
*/

MERGE INTO ph_erp_customers target
USING (
SELECT 1 customer_id, 'Acme Retail' customer_name, 'Acme Retail LLC' legal_name, 'it@acme-retail.example' contact_email, '+966500000001' contact_phone FROM dual
    UNION ALL SELECT 2, 'Gulf Health Group', 'Gulf Health Group Co.', 'systems@gulf-health.example', '+966500000002' FROM dual
    UNION ALL SELECT 3, 'Najd Logistics', 'Najd Logistics Company', 'ops@najd-logistics.example', '+966500000003' FROM dual
    UNION ALL SELECT 4, 'Riyadh Education Network', 'Riyadh Education Network', 'platform@riyadh-education.example', '+966500000004' FROM dual
    UNION ALL SELECT 5, 'Desert Finance House', 'Desert Finance House', 'digital@desert-finance.example', '+966500000005' FROM dual
    ) source
    ON (target.customer_id = source.customer_id)
    WHEN MATCHED THEN
    UPDATE SET
    target.customer_name = source.customer_name,
    target.legal_name = source.legal_name,
    target.contact_email = source.contact_email,
    target.contact_phone = source.contact_phone,
    target.is_active = 1,
    target.is_deleted = 0,
    target.deleted_by = NULL,
    target.deleted_at = NULL,
    target.updated_by = 1
    WHEN NOT MATCHED THEN
    INSERT (customer_id, customer_name, legal_name, contact_email, contact_phone, is_active, created_by)
    VALUES (source.customer_id, source.customer_name, source.legal_name, source.contact_email, source.contact_phone, 1, 1);

ALTER TABLE ph_erp_customers MODIFY customer_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
