/*
ProductHub Manager - Customer Module Tables and Constraints
Target DBMS: Oracle Database 21c+
*/

CREATE TABLE ph_erp_customers (
    customer_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(250 CHAR) NOT NULL,
    legal_name    VARCHAR2(250 CHAR),
    contact_email VARCHAR2(320 CHAR),
    contact_phone VARCHAR2(50 CHAR),
    is_active     NUMBER(1) DEFAULT 1 NOT NULL,
    is_deleted    NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_deleted IN (0, 1) ),
    created_by    NUMBER,
    created_at    TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by    NUMBER,
    updated_at    TIMESTAMP(3),
    deleted_by    NUMBER,
    deleted_at    TIMESTAMP(3),
    CONSTRAINT pk_ph_erp_customers PRIMARY KEY (customer_id)
);

------------------------------------------------------------
-- Active flag checks
------------------------------------------------------------

ALTER TABLE ph_erp_customers
ADD CONSTRAINT ck_ph_erp_customers_active CHECK ( is_active IN (0, 1) );
