/*
    ProductHub Manager - Oracle Tables and Constraints
    Target DBMS: Oracle Database 21c+

    Naming:
    - ERP/business tables use PH_ERP_ prefix.
    - Security/auth tables use PH_SEC_ prefix.
    - Lookup tables use _LKP postfix.
    - Default Arabic/English text is stored in *_EN and *_AR columns.
    - Additional languages are stored in PH_I18N_TEXTS by table/entity/field.
    - Active flags use: is_active NUMBER(1) DEFAULT 1 NOT NULL with CHECK (is_active IN (0, 1)).
    - Soft delete flags use: is_deleted NUMBER(1) DEFAULT 0 NOT NULL with CHECK (is_deleted IN (0, 1)).
*/

------------------------------------------------------------
-- Lookup tables
------------------------------------------------------------
create table ph_languages (
   language_code varchar2(20 char) not null,
   language_name varchar2(100 char) not null,
   native_name   varchar2(100 char),
   is_rtl        number(1) default 0 not null,
   is_default    number(1) default 0 not null,
   is_active     number(1) default 1 not null,
   is_deleted    number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at    timestamp(3) default systimestamp not null,
   updated_by    number,
   updated_at    timestamp(3),
   deleted_by    number,
   deleted_at    timestamp(3),
   constraint pk_ph_languages primary key ( language_code ),
   constraint ck_ph_languages_code check ( language_code = lower(language_code) ),
   constraint ck_ph_languages_flags
      check ( is_rtl in ( 0,
                          1 )
         and is_default in ( 0,
                             1 )
         and is_active in ( 0,
                            1 ) )
);

create table ph_i18n_texts (
   i18n_text_id  number(19) generated by default as identity,
   entity_name   varchar2(128 char) not null,
   entity_key    varchar2(400 char) not null,
   field_name    varchar2(128 char) not null,
   language_code varchar2(20 char) not null,
   text_value    varchar2(4000 char),
   is_deleted    number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at    timestamp(3) default systimestamp not null,
   updated_by    number,
   updated_at    timestamp(3),
   deleted_by    number,
   deleted_at    timestamp(3),
   constraint pk_ph_i18n_texts primary key ( i18n_text_id ),
   constraint uk_ph_i18n_texts unique ( entity_name,
                                        entity_key,
                                        field_name,
                                        language_code ),
   constraint fk_ph_i18n_language foreign key ( language_code )
      references ph_languages ( language_code ),
   constraint ck_ph_i18n_names
      check ( entity_name = upper(entity_name)
          and field_name = upper(field_name)
          and language_code = lower(language_code) )
);

create table ph_i18n_messages (
   message_code  varchar2(100 char) not null,
   language_code varchar2(20 char) not null,
   message_text  varchar2(4000 char) not null,
   is_deleted    number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at    timestamp(3) default systimestamp not null,
   updated_by    number,
   updated_at    timestamp(3),
   deleted_by    number,
   deleted_at    timestamp(3),
   constraint pk_ph_i18n_messages primary key ( message_code,
                                                language_code ),
   constraint fk_ph_i18n_msg_language foreign key ( language_code )
      references ph_languages ( language_code ),
   constraint ck_ph_i18n_msg_code check ( message_code = upper(message_code)
                                     and language_code = lower(language_code) )
);

create table ph_erp_pricing_unit_lkp (
   pricing_unit_id      number(10) generated by default as identity,
   pricing_unit_name_en varchar2(100 char) not null,
   pricing_unit_name_ar varchar2(100 char) not null,
   is_active            number(1) default 1 not null,
   is_deleted           number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at           timestamp(3) default systimestamp not null,
   updated_by           number,
   updated_at           timestamp(3),
   deleted_by           number,
   deleted_at           timestamp(3),
   constraint pk_ph_erp_pricing_unit_lkp primary key ( pricing_unit_id )
);

create table ph_erp_payment_cycle_lkp (
   payment_cycle_id      number(10) generated by default as identity,
   payment_cycle_name_en varchar2(100 char) not null,
   payment_cycle_name_ar varchar2(100 char) not null,
   months_count          number(3) not null,
   is_active             number(1) default 1 not null,
   is_deleted            number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at            timestamp(3) default systimestamp not null,
   updated_by            number,
   updated_at            timestamp(3),
   deleted_by            number,
   deleted_at            timestamp(3),
   constraint pk_ph_erp_pay_cycle_lkp primary key ( payment_cycle_id ),
   constraint ck_ph_erp_pay_cycle_months check ( months_count > 0 )
);

create table ph_sec_user_type_lkp (
   user_type_id      number(10) generated by default as identity,
   user_type_name_en varchar2(100 char) not null,
   user_type_name_ar varchar2(100 char) not null,
   is_active         number(1) default 1 not null,
   is_deleted        number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at        timestamp(3) default systimestamp not null,
   updated_by        number,
   updated_at        timestamp(3),
   deleted_by        number,
   deleted_at        timestamp(3),
   constraint pk_ph_sec_user_type_lkp primary key ( user_type_id )
);

create table ph_erp_platform_lkp (
   platform_id      number(10) generated by default as identity,
   platform_name_en varchar2(100 char) not null,
   platform_name_ar varchar2(100 char) not null,
   is_active        number(1) default 1 not null,
   is_deleted       number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at       timestamp(3) default systimestamp not null,
   updated_by       number,
   updated_at       timestamp(3),
   deleted_by       number,
   deleted_at       timestamp(3),
   constraint pk_ph_erp_platform_lkp primary key ( platform_id )
);

------------------------------------------------------------
-- ERP catalog tables
------------------------------------------------------------

create table ph_erp_products (
   product_id      number(19) generated by default as identity,
   product_name_en varchar2(200 char) not null,
   product_name_ar varchar2(200 char) not null,
   description_en  varchar2(1000 char),
   description_ar  varchar2(1000 char),
   is_active       number(1) default 1 not null,
   is_deleted      number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at      timestamp(3) default systimestamp not null,
   updated_by      number,
   updated_at      timestamp(3),
   deleted_by      number,
   deleted_at      timestamp(3),
   constraint pk_ph_erp_products primary key ( product_id )
);

create table ph_erp_product_module_seq (
   product_id     number(19) not null,
   next_module_id number(19) default 1 not null,
   is_deleted     number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at     timestamp(3) default systimestamp not null,
   updated_by     number,
   updated_at     timestamp(3),
   deleted_by     number,
   deleted_at     timestamp(3),
   constraint pk_ph_erp_product_module_seq primary key ( product_id ),
   constraint fk_ph_erp_pms_product foreign key ( product_id )
      references ph_erp_products ( product_id ),
   constraint ck_ph_erp_pms_next check ( next_module_id >= 1 )
)
organization index;

create table ph_erp_modules (
   product_id     number(19) not null,
   module_id      number(19) not null,
   module_name_en varchar2(200 char) not null,
   module_name_ar varchar2(200 char) not null,
   description_en varchar2(1000 char),
   description_ar varchar2(1000 char),
   display_order  number(10) default 0 not null,
   is_active      number(1) default 1 not null,
   is_deleted     number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at     timestamp(3) default systimestamp not null,
   updated_by     number,
   updated_at     timestamp(3),
   deleted_by     number,
   deleted_at     timestamp(3),
   constraint pk_ph_erp_modules primary key ( product_id,
                                              module_id ),
   constraint fk_ph_erp_modules_product foreign key ( product_id )
      references ph_erp_products ( product_id )
);

create table ph_erp_module_platforms (
   product_id  number(19) not null,
   module_id   number(19) not null,
   platform_id number(10) not null,
   is_active   number(1) default 1 not null,
   is_deleted  number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at  timestamp(3) default systimestamp not null,
   updated_by  number,
   updated_at  timestamp(3),
   deleted_by  number,
   deleted_at  timestamp(3),
   constraint pk_ph_erp_module_platforms primary key ( product_id,
                                                       module_id,
                                                       platform_id ),
   constraint fk_ph_erp_mp_module
      foreign key ( product_id,
                    module_id )
         references ph_erp_modules ( product_id,
                                     module_id ),
   constraint fk_ph_erp_mp_platform foreign key ( platform_id )
      references ph_erp_platform_lkp ( platform_id )
);

create table ph_erp_module_feature_seq (
   product_id      number(19) not null,
   module_id       number(19) not null,
   platform_id     number(10) not null,
   next_feature_id number(19) default 1 not null,
   is_deleted      number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at      timestamp(3) default systimestamp not null,
   updated_by      number,
   updated_at      timestamp(3),
   deleted_by      number,
   deleted_at      timestamp(3),
   constraint pk_ph_erp_module_feature_seq primary key ( product_id,
                                                         module_id,
                                                         platform_id ),
   constraint fk_ph_erp_mfs_mod_plat
      foreign key ( product_id,
                    module_id,
                    platform_id )
         references ph_erp_module_platforms ( product_id,
                                              module_id,
                                              platform_id ),
   constraint ck_ph_erp_mfs_next check ( next_feature_id >= 1 )
)
organization index;

create table ph_erp_features (
   product_id      number(19) not null,
   module_id       number(19) not null,
   platform_id     number(10) not null,
   feature_id      number(19) not null,
   feature_name_en varchar2(200 char) not null,
   feature_name_ar varchar2(200 char) not null,
   description_en  varchar2(1000 char),
   description_ar  varchar2(1000 char),
   price           number(18,4) not null,
   pricing_unit_id number(10) not null,
   usage_unit      varchar2(50 char) default 'USE' not null,
   display_order   number(10) default 0 not null,
   is_active       number(1) default 1 not null,
   is_deleted      number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at      timestamp(3) default systimestamp not null,
   updated_by      number,
   updated_at      timestamp(3),
   deleted_by      number,
   deleted_at      timestamp(3),
   constraint pk_ph_erp_features
      primary key ( product_id,
                    module_id,
                    platform_id,
                    feature_id ),
   constraint fk_ph_erp_features_mod_plat
      foreign key ( product_id,
                    module_id,
                    platform_id )
         references ph_erp_module_platforms ( product_id,
                                              module_id,
                                              platform_id ),
   constraint fk_ph_erp_features_unit foreign key ( pricing_unit_id )
      references ph_erp_pricing_unit_lkp ( pricing_unit_id ),
   constraint ck_ph_erp_features_price check ( price >= 0 )
);

------------------------------------------------------------
-- ERP customer and contract tables
------------------------------------------------------------

create table ph_erp_customers (
   customer_id   number(19) generated by default as identity,
   customer_name varchar2(250 char) not null,
   legal_name    varchar2(250 char),
   contact_email varchar2(320 char),
   contact_phone varchar2(50 char),
   is_active     number(1) default 1 not null,
   is_deleted    number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at    timestamp(3) default systimestamp not null,
   updated_by    number,
   updated_at    timestamp(3),
   deleted_by    number,
   deleted_at    timestamp(3),
   constraint pk_ph_erp_customers primary key ( customer_id )
);

create table ph_erp_contracts (
   contract_id   number(19) generated by default as identity,
   contract_no   varchar2(80 char) not null,
   customer_id   number(19) not null,
   product_id    number(19) not null,
   start_date    date not null,
   end_date      date,
   payment_cycle number(10) not null,
   is_active     number(1) default 1 not null,
   notes_en      varchar2(1000 char),
   notes_ar      varchar2(1000 char),
   is_deleted    number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at    timestamp(3) default systimestamp not null,
   updated_by    number,
   updated_at    timestamp(3),
   deleted_by    number,
   deleted_at    timestamp(3),
   constraint pk_ph_erp_contracts primary key ( contract_id ),
   constraint uk_ph_erp_contracts_no unique ( contract_no ),
   constraint uk_ph_erp_contracts_prod unique ( contract_id,
                                                product_id ),
   constraint uk_ph_erp_contracts_cprod unique ( contract_id,
                                                 customer_id,
                                                 product_id ),
   constraint fk_ph_erp_contract_customer foreign key ( customer_id )
      references ph_erp_customers ( customer_id ),
   constraint fk_ph_erp_contract_product foreign key ( product_id )
      references ph_erp_products ( product_id ),
   constraint fk_ph_erp_contract_cycle foreign key ( payment_cycle )
      references ph_erp_payment_cycle_lkp ( payment_cycle_id ),
   constraint ck_ph_erp_contract_dates
      check ( end_date is null
          or end_date >= start_date )
);

create table ph_erp_contract_urls (
   contract_url_id number(19) generated by default as identity,
   contract_id     number(19) not null,
   access_url      varchar2(1000 char) not null,
   is_primary      number(1) default 1 not null,
   is_active       number(1) default 1 not null,
   is_deleted      number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at      timestamp(3) default systimestamp not null,
   updated_by      number,
   updated_at      timestamp(3),
   deleted_by      number,
   deleted_at      timestamp(3),
   constraint pk_ph_erp_contract_urls primary key ( contract_url_id ),
   constraint uk_ph_erp_contract_url unique ( contract_id,
                                              access_url ),
   constraint fk_ph_erp_cu_contract foreign key ( contract_id )
      references ph_erp_contracts ( contract_id ),
   constraint ck_ph_erp_cu_flags
      check ( is_primary in ( 0,
                              1 )
         and is_active in ( 0,
                            1 ) )
);

create table ph_erp_contract_modules (
   contract_id    number(19) not null,
   product_id     number(19) not null,
   module_id      number(19) not null,
   is_active      number(1) default 1 not null,
   effective_from date default trunc(sysdate) not null,
   effective_to   date,
   is_deleted     number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at     timestamp(3) default systimestamp not null,
   updated_by     number,
   updated_at     timestamp(3),
   deleted_by     number,
   deleted_at     timestamp(3),
   constraint pk_ph_erp_contract_modules primary key ( contract_id,
                                                       module_id ),
   constraint uk_ph_erp_contract_modules unique ( contract_id,
                                                  product_id,
                                                  module_id ),
   constraint fk_ph_erp_cm_contract
      foreign key ( contract_id,
                    product_id )
         references ph_erp_contracts ( contract_id,
                                       product_id ),
   constraint fk_ph_erp_cm_module
      foreign key ( product_id,
                    module_id )
         references ph_erp_modules ( product_id,
                                     module_id ),
   constraint ck_ph_erp_cm_dates
      check ( effective_to is null
          or effective_to >= effective_from )
);

create table ph_erp_contract_platforms (
   contract_id    number(19) not null,
   product_id     number(19) not null,
   module_id      number(19) not null,
   platform_id    number(10) not null,
   is_active      number(1) default 1 not null,
   effective_from date default trunc(sysdate) not null,
   effective_to   date,
   is_deleted     number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at     timestamp(3) default systimestamp not null,
   updated_by     number,
   updated_at     timestamp(3),
   deleted_by     number,
   deleted_at     timestamp(3),
   constraint pk_ph_erp_contract_platforms
      primary key ( contract_id,
                    product_id,
                    module_id,
                    platform_id ),
   constraint fk_ph_erp_cp_contract_mod
      foreign key ( contract_id,
                    product_id,
                    module_id )
         references ph_erp_contract_modules ( contract_id,
                                              product_id,
                                              module_id ),
   constraint fk_ph_erp_cp_module_platform
      foreign key ( product_id,
                    module_id,
                    platform_id )
         references ph_erp_module_platforms ( product_id,
                                              module_id,
                                              platform_id ),
   constraint ck_ph_erp_cp_dates
      check ( effective_to is null
          or effective_to >= effective_from )
);

create table ph_erp_contract_features (
   contract_id    number(19) not null,
   product_id     number(19) not null,
   module_id      number(19) not null,
   platform_id    number(10) not null,
   feature_id     number(19) not null,
   agreed_price   number(18,4),
   is_active      number(1) default 1 not null,
   effective_from date default trunc(sysdate) not null,
   effective_to   date,
   is_deleted     number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at     timestamp(3) default systimestamp not null,
   updated_by     number,
   updated_at     timestamp(3),
   deleted_by     number,
   deleted_at     timestamp(3),
   constraint pk_ph_erp_contract_features
      primary key ( contract_id,
                    product_id,
                    module_id,
                    platform_id,
                    feature_id ),
   constraint fk_ph_erp_cf_contract_platform
      foreign key ( contract_id,
                    product_id,
                    module_id,
                    platform_id )
         references ph_erp_contract_platforms ( contract_id,
                                                product_id,
                                                module_id,
                                                platform_id ),
   constraint fk_ph_erp_cf_feature
      foreign key ( product_id,
                    module_id,
                    platform_id,
                    feature_id )
         references ph_erp_features ( product_id,
                                      module_id,
                                      platform_id,
                                      feature_id ),
   constraint ck_ph_erp_cf_price
      check ( agreed_price is null
          or agreed_price >= 0 ),
   constraint ck_ph_erp_cf_dates
      check ( effective_to is null
          or effective_to >= effective_from )
);

------------------------------------------------------------
-- Security tables
------------------------------------------------------------

create table ph_sec_object_type_lkp (
   object_type_id      number(10) generated by default as identity,
   object_type_name_en varchar2(100 char) not null,
   object_type_name_ar varchar2(100 char) not null,
   is_active           number(1) default 1 not null,
   is_deleted          number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at          timestamp(3) default systimestamp not null,
   updated_by          number,
   updated_at          timestamp(3),
   deleted_by          number,
   deleted_at          timestamp(3),
   constraint pk_ph_sec_object_type_lkp primary key ( object_type_id )
);

create table ph_sec_objects (
   object_id        number(19) generated by default as identity,
   parent_object_id number(19),
   object_name      varchar2(128 char) not null,
   object_type_id   number(10) not null,
   object_path      varchar2(300 char) not null,
   display_name_en  varchar2(200 char) not null,
   display_name_ar  varchar2(200 char) not null,
   description_en   varchar2(500 char),
   description_ar   varchar2(500 char),
   is_active        number(1) default 1 not null,
   is_deleted       number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at       timestamp(3) default systimestamp not null,
   updated_by       number,
   updated_at       timestamp(3),
   deleted_by       number,
   deleted_at       timestamp(3),
   constraint pk_ph_sec_objects primary key ( object_id ),
   constraint uk_ph_sec_objects_name unique ( object_name ),
   constraint uk_ph_sec_objects_path unique ( object_path ),
   constraint fk_ph_sec_objects_parent foreign key ( parent_object_id )
      references ph_sec_objects ( object_id ),
   constraint fk_ph_sec_objects_type foreign key ( object_type_id )
      references ph_sec_object_type_lkp ( object_type_id ),
   constraint ck_ph_sec_objects_parent
      check ( parent_object_id is null
          or parent_object_id <> object_id )
);

create table ph_sec_actions (
   action_id       number(19) generated by default as identity,
   action_name     varchar2(80 char) not null,
   display_name_en varchar2(150 char) not null,
   display_name_ar varchar2(150 char) not null,
   description_en  varchar2(500 char),
   description_ar  varchar2(500 char),
   is_active       number(1) default 1 not null,
   is_deleted      number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at      timestamp(3) default systimestamp not null,
   updated_by      number,
   updated_at      timestamp(3),
   deleted_by      number,
   deleted_at      timestamp(3),
   constraint pk_ph_sec_actions primary key ( action_id ),
   constraint uk_ph_sec_actions_name unique ( action_name )
);

create table ph_sec_permissions (
   permission_id      number(19) generated by default as identity,
   object_id          number(19) not null,
   action_id          number(19) not null,
   permission_name_en varchar2(200 char) not null,
   permission_name_ar varchar2(200 char) not null,
   description_en     varchar2(500 char),
   description_ar     varchar2(500 char),
   is_active          number(1) default 1 not null,
   is_deleted         number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at         timestamp(3) default systimestamp not null,
   updated_by         number,
   updated_at         timestamp(3),
   deleted_by         number,
   deleted_at         timestamp(3),
   constraint pk_ph_sec_permissions primary key ( permission_id ),
   constraint uk_ph_sec_permissions unique ( object_id,
                                             action_id ),
   constraint fk_ph_sec_perm_object foreign key ( object_id )
      references ph_sec_objects ( object_id ),
   constraint fk_ph_sec_perm_action foreign key ( action_id )
      references ph_sec_actions ( action_id )
);

create table ph_sec_apex_page_type_lkp (
   apex_page_type_id      number(10) generated by default as identity,
   apex_page_type_code    varchar2(50 char) not null,
   apex_page_type_name_en varchar2(100 char) not null,
   apex_page_type_name_ar varchar2(100 char) not null,
   is_active             number(1) default 1 not null,
   is_deleted            number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at            timestamp(3) default systimestamp not null,
   updated_by            number,
   updated_at            timestamp(3),
   deleted_by            number,
   deleted_at            timestamp(3),
   constraint pk_ph_sec_apex_page_type primary key ( apex_page_type_id ),
   constraint uk_ph_sec_apex_page_type_code unique ( apex_page_type_code ),
   constraint ck_ph_sec_apex_ptype_active check ( is_active in ( 0,
                                                                 1 ) )
);

create table ph_sec_users (
   user_id              number(19) generated by default as identity,
   customer_id          number(19),
   user_type            number(10) not null,
   email                varchar2(320 char) not null,
   display_name         varchar2(200 char) not null,
   password_hash        raw(512),
   password_salt        raw(256),
   must_change_password number(1) default 1 not null,
   is_initial_admin     number(1) default 0 not null,
   is_active            number(1) default 1 not null,
   last_login_at        timestamp(3),
   is_deleted           number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at           timestamp(3) default systimestamp not null,
   updated_by           number,
   updated_at           timestamp(3),
   deleted_by           number,
   deleted_at           timestamp(3),
   constraint pk_ph_sec_users primary key ( user_id ),
   constraint uk_ph_sec_users_email unique ( email ),
   constraint fk_ph_sec_users_customer foreign key ( customer_id )
      references ph_erp_customers ( customer_id ),
   constraint fk_ph_sec_users_type foreign key ( user_type )
      references ph_sec_user_type_lkp ( user_type_id ),
   /*constraint fk_ph_sec_users_created_by foreign key ( created_by )
      references ph_sec_users ( user_id ),
   constraint fk_ph_sec_users_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id ),*/
   constraint ck_ph_sec_users_email_lower check ( email = lower(email) ),
   constraint ck_ph_sec_users_flags
      check ( must_change_password in ( 0,
                                        1 )
         and is_initial_admin in ( 0,
                                   1 ) )
);

create table ph_sec_user_preferences (
   user_id          number(19) not null,
   preference_code  varchar2(80 char) not null,
   preference_value varchar2(4000 char),
   value_type       varchar2(20 char) default 'STRING' not null,
   is_active        number(1) default 1 not null,
   is_deleted       number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at       timestamp(3) default systimestamp not null,
   updated_by       number,
   updated_at       timestamp(3),
   deleted_by       number,
   deleted_at       timestamp(3),
   constraint pk_ph_sec_user_preferences primary key ( user_id,
                                                       preference_code ),
   constraint fk_ph_sec_user_pref_user foreign key ( user_id )
      references ph_sec_users ( user_id ),
  /* constraint fk_ph_sec_user_pref_created foreign key ( created_by )
      references ph_sec_users ( user_id ),
   constraint fk_ph_sec_user_pref_updated foreign key ( updated_by )
      references ph_sec_users ( user_id ),*/
   constraint ck_ph_sec_user_pref_code check ( preference_code = upper(preference_code) ),
   constraint ck_ph_sec_user_pref_type check ( value_type in ( 'STRING',
                                                               'NUMBER',
                                                               'BOOLEAN',
                                                               'JSON' ) ),
   constraint ck_ph_sec_user_pref_active check ( is_active in ( 0,
                                                                1 ) )
);

create table ph_sec_apex_pages (
   apex_page_id      number(19) generated by default as identity,
   apex_app_id       number(10) not null,
   apex_page_no      number(10) not null,
   apex_page_type_id number(10) not null,
   page_alias        varchar2(128 char),
   page_name_en      varchar2(200 char) not null,
   page_name_ar      varchar2(200 char) not null,
   object_path       varchar2(300 char),
   access_mode       varchar2(20 char) default 'ANY' not null,
   is_public         number(1) default 0 not null,
   is_active         number(1) default 1 not null,
   is_deleted        number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at        timestamp(3) default systimestamp not null,
   updated_by        number,
   updated_at        timestamp(3),
   deleted_by        number,
   deleted_at        timestamp(3),
   constraint pk_ph_sec_apex_pages primary key ( apex_page_id ),
   constraint uk_ph_sec_apex_pages_app_page unique ( apex_app_id,
                                                     apex_page_no ),
   constraint uk_ph_sec_apex_pages_alias unique ( apex_app_id,
                                                  page_alias ),
   constraint fk_ph_sec_apex_pages_type foreign key ( apex_page_type_id )
      references ph_sec_apex_page_type_lkp ( apex_page_type_id ),
   /*constraint fk_ph_sec_apex_pages_created foreign key ( created_by )
      references ph_sec_users ( user_id ),
   constraint fk_ph_sec_apex_pages_updated foreign key ( updated_by )
      references ph_sec_users ( user_id ),*/
   constraint ck_ph_sec_apex_pages_ids
      check ( apex_app_id > 0
         and apex_page_no >= 0 ),
   constraint ck_ph_sec_apex_pages_mode check ( access_mode in ( 'ANY',
                                                                 'ALL' ) ),
   constraint ck_ph_sec_apex_pages_flags
      check ( is_public in ( 0,
                             1 )
         and is_active in ( 0,
                            1 ) )
);

create table ph_sec_apex_page_permissions (
   apex_page_id            number(19) not null,
   permission_id           number(19) not null,
   is_an_access_permission number(1) default 1 not null,
   is_active               number(1) default 1 not null,
   is_deleted              number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at              timestamp(3) default systimestamp not null,
   updated_by              number,
   updated_at              timestamp(3),
   deleted_by              number,
   deleted_at              timestamp(3),
   constraint pk_ph_sec_apex_page_perm primary key ( apex_page_id,
                                                     permission_id ),
   constraint fk_ph_sec_app_perm_page foreign key ( apex_page_id )
      references ph_sec_apex_pages ( apex_page_id ),
   constraint fk_ph_sec_app_perm_perm foreign key ( permission_id )
      references ph_sec_permissions ( permission_id ),
   /*constraint fk_ph_sec_app_perm_created foreign key ( created_by )
      references ph_sec_users ( user_id ),
   constraint fk_ph_sec_app_perm_updated foreign key ( updated_by )
      references ph_sec_users ( user_id ),*/
   constraint ck_ph_sec_app_perm_active check ( is_active in ( 0,
                                                               1 ) ),
   constraint ck_ph_sec_app_perm_access check ( is_an_access_permission in ( 0,
                                                                             1 ) )
);

create table ph_sec_roles (
   role_id        number(19) generated by default as identity,
   role_name_en   varchar2(150 char) not null,
   role_name_ar   varchar2(150 char) not null,
   description_en varchar2(500 char),
   description_ar varchar2(500 char),
   user_type      number(10) not null,
   is_system_role number(1) default 0 not null,
   is_active      number(1) default 1 not null,
   is_deleted     number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at     timestamp(3) default systimestamp not null,
   updated_by     number,
   updated_at     timestamp(3),
   deleted_by     number,
   deleted_at     timestamp(3),
   constraint pk_ph_sec_roles primary key ( role_id ),
   constraint fk_ph_sec_roles_type foreign key ( user_type )
      references ph_sec_user_type_lkp ( user_type_id ),
/*   constraint fk_ph_sec_roles_created_by foreign key ( created_by )
      references ph_sec_users ( user_id ),
   constraint fk_ph_sec_roles_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id ),*/
   constraint ck_ph_sec_roles_system check ( is_system_role in ( 0,
                                                                 1 ) )
);

create table ph_sec_role_permissions (
   role_id       number(19) not null,
   permission_id number(19) not null,
   is_deleted    number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at    timestamp(3) default systimestamp not null,
   updated_by    number,
   updated_at    timestamp(3),
   deleted_by    number,
   deleted_at    timestamp(3),
   constraint pk_ph_sec_role_permissions primary key ( role_id,
                                                       permission_id ),
   constraint fk_ph_sec_rp_role foreign key ( role_id )
      references ph_sec_roles ( role_id ),
   constraint fk_ph_sec_rp_permission foreign key ( permission_id )
      references ph_sec_permissions ( permission_id )/*,
   constraint fk_ph_sec_rp_created_by foreign key ( created_by )
      references ph_sec_users ( user_id )*/
);

create table ph_sec_user_roles (
   user_id     number(19) not null,
   role_id     number(19) not null,
   assigned_by number(19),
   assigned_at timestamp(3) default systimestamp not null,
   is_deleted  number(1) default 0 not null check ( is_deleted in ( 0, 1 ) ),
   created_by    number,
   created_at  timestamp(3) default systimestamp not null,
   updated_by  number,
   updated_at  timestamp(3),
   deleted_by  number,
   deleted_at  timestamp(3),
   constraint pk_ph_sec_user_roles primary key ( user_id,
                                                 role_id ),
   constraint fk_ph_sec_ur_user foreign key ( user_id )
      references ph_sec_users ( user_id ),
   constraint fk_ph_sec_ur_role foreign key ( role_id )
      references ph_sec_roles ( role_id )/*,
   constraint fk_ph_sec_ur_assigned_by foreign key ( assigned_by )
      references ph_sec_users ( user_id )*/
);

------------------------------------------------------------
-- Standard active flag checks
------------------------------------------------------------

alter table ph_erp_pricing_unit_lkp
   add constraint ck_ph_erp_price_unit_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_payment_cycle_lkp
   add constraint ck_ph_erp_pay_cycle_active check ( is_active in ( 0, 1 ) );

alter table ph_sec_user_type_lkp
   add constraint ck_ph_sec_user_type_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_platform_lkp
   add constraint ck_ph_erp_platform_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_products
   add constraint ck_ph_erp_products_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_modules
   add constraint ck_ph_erp_modules_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_module_platforms
   add constraint ck_ph_erp_mp_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_features
   add constraint ck_ph_erp_features_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_customers
   add constraint ck_ph_erp_customers_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_contracts
   add constraint ck_ph_erp_contracts_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_contract_modules
   add constraint ck_ph_erp_cm_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_contract_platforms
   add constraint ck_ph_erp_cp_active check ( is_active in ( 0, 1 ) );

alter table ph_erp_contract_features
   add constraint ck_ph_erp_cf_active check ( is_active in ( 0, 1 ) );

alter table ph_sec_object_type_lkp
   add constraint ck_ph_sec_obj_type_active check ( is_active in ( 0, 1 ) );

alter table ph_sec_objects
   add constraint ck_ph_sec_objects_active check ( is_active in ( 0, 1 ) );

alter table ph_sec_actions
   add constraint ck_ph_sec_actions_active check ( is_active in ( 0, 1 ) );

alter table ph_sec_permissions
   add constraint ck_ph_sec_permissions_active check ( is_active in ( 0, 1 ) );

alter table ph_sec_users
   add constraint ck_ph_sec_users_active check ( is_active in ( 0, 1 ) );

alter table ph_sec_roles
   add constraint ck_ph_sec_roles_active check ( is_active in ( 0, 1 ) );

------------------------------------------------------------
-- Audit user foreign keys
------------------------------------------------------------
/*
alter table ph_i18n_texts
   add constraint fk_ph_i18n_texts_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_i18n_texts
   add constraint fk_ph_i18n_texts_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_i18n_messages
   add constraint fk_ph_i18n_msg_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_i18n_messages
   add constraint fk_ph_i18n_msg_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_erp_products
   add constraint fk_ph_erp_prod_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_erp_products
   add constraint fk_ph_erp_prod_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_erp_modules
   add constraint fk_ph_erp_mod_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_erp_modules
   add constraint fk_ph_erp_mod_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_erp_module_platforms
   add constraint fk_ph_erp_mp_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_erp_module_platforms
   add constraint fk_ph_erp_mp_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_erp_features
   add constraint fk_ph_erp_feat_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_erp_features
   add constraint fk_ph_erp_feat_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_erp_customers
   add constraint fk_ph_erp_cust_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_erp_customers
   add constraint fk_ph_erp_cust_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_erp_contract_urls
   add constraint fk_ph_erp_cu_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_erp_contract_urls
   add constraint fk_ph_erp_cu_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_erp_contracts
   add constraint fk_ph_erp_cont_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_erp_contracts
   add constraint fk_ph_erp_cont_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_erp_contract_modules
   add constraint fk_ph_erp_cm_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_erp_contract_modules
   add constraint fk_ph_erp_cm_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_erp_contract_platforms
   add constraint fk_ph_erp_cp_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_erp_contract_platforms
   add constraint fk_ph_erp_cp_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );

alter table ph_erp_contract_features
   add constraint fk_ph_erp_cf_created_by foreign key ( created_by )
      references ph_sec_users ( user_id );

alter table ph_erp_contract_features
   add constraint fk_ph_erp_cf_updated_by foreign key ( updated_by )
      references ph_sec_users ( user_id );*/
